spring:
  application:
    name: java-spring-boot-interview
  jpa:
#    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
#   the following block is necessary to prevent the entity classes from overwriting the schema setup from the schema.sql
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:customerdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false


